name: Multi-Jobs workflow

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      - name: Print Hello world
        run: echo "Hello World"

  build:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Print Job2
        run: echo "This is job 2"

  deploy:
    runs-on: ubuntu-latest
    needs: [test, build]
    steps:
      - name: Print job3
        run: echo "This is job3"
